version: "3"
services:
  db:
    image: mongo
  web:
    build: ./web
    environment:
      - DJANGO_SETTINGS_MODULE=letters_in_image.settings.prod
    command: /usr/local/bin/gunicorn letters_in_image.wsgi:application -w 3 -b :8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet:
